Bump the rails group with 4 updates (#1658)
Bumps the rails group with 4 updates:
[@rails/actioncable](https://github.com/rails/rails),
[@rails/actiontext](https://github.com/rails/rails),
[@rails/activestorage](https://github.com/rails/rails) and
[@rails/ujs](https://github.com/rails/rails).

Updates `@rails/actioncable` from 7.2.0 to 7.2.100
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases"><code>@​rails/actioncable</code>'s
releases</a>.</em></p>
<blockquote>
<h2>7.2.1</h2>
<h2>Active Support</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix detection for <code>enum</code> columns with parallelized tests
and PostgreSQL.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Allow to eager load nested nil associations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix swallowing ignore order warning when batching using
<code>BatchEnumerator</code>.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix memory bloat on the connection pool when using the Fiber
<code>IsolatedExecutionState</code>.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Restore inferred association class with the same modularized
name.</p>
<p><em>Justin Ko</em></p>
</li>
<li>
<p>Fix <code>ActiveRecord::Base.inspect</code> to properly explain how
to load schema information.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Check invalid <code>enum</code> options for the new syntax.</p>
<p>The options using <code>_</code> prefix in the old syntax are invalid
in the new syntax.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Fix
<code>ActiveRecord::Encryption::EncryptedAttributeType#type</code> to
return
actual cast type.</p>
<p><em>Vasiliy Ermolovich</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/rails/rails/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `@rails/actiontext` from 7.2.0 to 7.2.100
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases"><code>@​rails/actiontext</code>'s
releases</a>.</em></p>
<blockquote>
<h2>7.2.1</h2>
<h2>Active Support</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix detection for <code>enum</code> columns with parallelized tests
and PostgreSQL.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Allow to eager load nested nil associations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix swallowing ignore order warning when batching using
<code>BatchEnumerator</code>.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix memory bloat on the connection pool when using the Fiber
<code>IsolatedExecutionState</code>.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Restore inferred association class with the same modularized
name.</p>
<p><em>Justin Ko</em></p>
</li>
<li>
<p>Fix <code>ActiveRecord::Base.inspect</code> to properly explain how
to load schema information.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Check invalid <code>enum</code> options for the new syntax.</p>
<p>The options using <code>_</code> prefix in the old syntax are invalid
in the new syntax.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Fix
<code>ActiveRecord::Encryption::EncryptedAttributeType#type</code> to
return
actual cast type.</p>
<p><em>Vasiliy Ermolovich</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/rails/rails/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `@rails/activestorage` from 7.2.0 to 7.2.100
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases"><code>@​rails/activestorage</code>'s
releases</a>.</em></p>
<blockquote>
<h2>7.2.1</h2>
<h2>Active Support</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix detection for <code>enum</code> columns with parallelized tests
and PostgreSQL.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Allow to eager load nested nil associations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix swallowing ignore order warning when batching using
<code>BatchEnumerator</code>.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix memory bloat on the connection pool when using the Fiber
<code>IsolatedExecutionState</code>.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Restore inferred association class with the same modularized
name.</p>
<p><em>Justin Ko</em></p>
</li>
<li>
<p>Fix <code>ActiveRecord::Base.inspect</code> to properly explain how
to load schema information.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Check invalid <code>enum</code> options for the new syntax.</p>
<p>The options using <code>_</code> prefix in the old syntax are invalid
in the new syntax.</p>
<p><em>Rafael Mendonça França</em></p>
</li>
<li>
<p>Fix
<code>ActiveRecord::Encryption::EncryptedAttributeType#type</code> to
return
actual cast type.</p>
<p><em>Vasiliy Ermolovich</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/rails/rails/commits">compare view</a></li>
</ul>
</details>
<br />

Updates `@rails/ujs` from 7.1.3 to 7.1.400
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases"><code>@​rails/ujs</code>'s
releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for
<code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by
default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/rails/rails/commits">compare view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>